import builtins
from contextlib import ContextDecorator
from os import PathLike
from typing import Any, Iterable, Optional, Sequence, Tuple, Union

__version__: str

class dtype:
    def __repr__(self) -> str: ...

class device:
    type: str
    index: Optional[int]
    def __init__(
        self, device: Union[str, device], index: Optional[int] = ...
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

float32: dtype
float64: dtype
bfloat16: dtype
int8: dtype
float: dtype
double: dtype
F32: dtype
F64: dtype
BF16: dtype
I8: dtype

DeviceLike = Union[str, device]
DTypeLike = Union[str, dtype]
Shape = Sequence[int]

class Tensor:
    shape: Tuple[int, ...]
    dtype: dtype
    device: device
    ndim: int
    requires_grad: bool
    is_leaf: bool
    grad: Optional[Tensor]
    grad_fn: Optional[str]
    data: Tensor
    T: Tensor
    _version: int
    _is_parameter: bool

    def __init__(
        self,
        data: Any,
        shape: Optional[Shape] = ...,
        dtype: Optional[DTypeLike] = ...,
        *,
        device: Optional[DeviceLike] = ...,
        requires_grad: bool = ...,
    ) -> None: ...
    def numel(self) -> int: ...
    def dim(self) -> int: ...
    def size(self, dim: Optional[int] = ...) -> Union[int, Tuple[int, ...]]: ...
    def item(self) -> Union[int, builtins.float]: ...
    def to_list(self) -> list[builtins.float]: ...
    def tolist(self) -> Any: ...
    def backward(
        self,
        gradient: Optional[Tensor] = ...,
        retain_graph: Optional[bool] = ...,
        create_graph: bool = ...,
    ) -> None: ...
    def requires_grad_(self, value: bool = ...) -> Tensor: ...
    def retain_grad(self) -> None: ...
    def zero_grad(self) -> None: ...
    def detach(self) -> Tensor: ...
    def clone(self) -> Tensor: ...
    def copy_(self, source: Tensor) -> Tensor: ...
    def fill_(self, value: builtins.float) -> None: ...
    def to(
        self,
        device: Optional[Union[DeviceLike, dtype, Tensor]] = ...,
        dtype: Optional[DTypeLike] = ...,
        non_blocking: bool = ...,
        copy: bool = ...,
    ) -> Tensor: ...
    def cpu(self) -> Tensor: ...
    def cuda(self, device: Optional[int] = ...) -> Tensor: ...
    def float(self) -> Tensor: ...
    def double(self) -> Tensor: ...
    def bfloat16(self) -> Tensor: ...
    def add(self, other: Union[Tensor, builtins.float]) -> Tensor: ...
    def sub(self, other: Union[Tensor, builtins.float]) -> Tensor: ...
    def mul(self, other: Union[Tensor, builtins.float]) -> Tensor: ...
    def div(self, other: Union[Tensor, builtins.float]) -> Tensor: ...
    def matmul(self, other: Tensor) -> Tensor: ...
    def sum(self, dim: Optional[int] = ..., keepdim: bool = ...) -> Tensor: ...
    def mean(self, dim: Optional[int] = ..., keepdim: bool = ...) -> Tensor: ...
    def reshape(self, shape: Shape) -> Tensor: ...
    def view(self, shape: Shape) -> Tensor: ...
    def flatten(self, start_dim: int = ..., end_dim: int = ...) -> Tensor: ...
    def squeeze(self, dim: Optional[int] = ...) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def transpose(self, dim0: int, dim1: int) -> Tensor: ...
    def is_contiguous(self) -> bool: ...
    def contiguous(self) -> Tensor: ...
    def relu(self) -> Tensor: ...
    def gelu(self) -> Tensor: ...
    def sigmoid(self) -> Tensor: ...
    def tanh(self) -> Tensor: ...
    def exp(self) -> Tensor: ...
    def log(self) -> Tensor: ...
    def sqrt(self) -> Tensor: ...
    def rsqrt(self) -> Tensor: ...
    def square(self) -> Tensor: ...
    def softmax(self, dim: Optional[int] = ...) -> Tensor: ...
    def log_softmax(self, dim: Optional[int] = ...) -> Tensor: ...
    def mse_loss(self, target: Tensor) -> Tensor: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Tensor: ...
    def __add__(self, other: Union[Tensor, builtins.float]) -> Tensor: ...
    def __sub__(self, other: Union[Tensor, builtins.float]) -> Tensor: ...
    def __mul__(self, other: Union[Tensor, builtins.float]) -> Tensor: ...
    def __truediv__(self, other: Union[Tensor, builtins.float]) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def __neg__(self) -> Tensor: ...

class _CudaNamespace:
    def is_available(self) -> bool: ...
    def device_count(self) -> int: ...

cuda: _CudaNamespace

def tensor(
    data: Any,
    shape: Optional[Shape] = ...,
    dtype: Optional[DTypeLike] = ...,
    *,
    device: Optional[DeviceLike] = ...,
    requires_grad: bool = ...,
) -> Tensor: ...
def zeros(
    shape: Shape,
    dtype: Optional[DTypeLike] = ...,
    *,
    device: Optional[DeviceLike] = ...,
    requires_grad: bool = ...,
) -> Tensor: ...
def ones(
    shape: Shape,
    dtype: Optional[DTypeLike] = ...,
    *,
    device: Optional[DeviceLike] = ...,
    requires_grad: bool = ...,
) -> Tensor: ...
def full(
    shape: Shape,
    fill_value: builtins.float,
    dtype: Optional[DTypeLike] = ...,
    *,
    device: Optional[DeviceLike] = ...,
    requires_grad: bool = ...,
) -> Tensor: ...
def rand(
    shape: Shape,
    *,
    min: builtins.float = ...,
    max: builtins.float = ...,
    seed: int = ...,
    dtype: Optional[DTypeLike] = ...,
    device: Optional[DeviceLike] = ...,
    requires_grad: bool = ...,
) -> Tensor: ...
def randn(
    shape: Shape,
    *,
    seed: int = ...,
    dtype: Optional[DTypeLike] = ...,
    device: Optional[DeviceLike] = ...,
    requires_grad: bool = ...,
) -> Tensor: ...
def arange(
    start: builtins.float,
    stop: Optional[builtins.float] = ...,
    step: builtins.float = ...,
    dtype: Optional[DTypeLike] = ...,
    *,
    device: Optional[DeviceLike] = ...,
    requires_grad: bool = ...,
) -> Tensor: ...
def eye(
    n: int,
    m: Optional[int] = ...,
    dtype: Optional[DTypeLike] = ...,
    *,
    device: Optional[DeviceLike] = ...,
    requires_grad: bool = ...,
) -> Tensor: ...
def matmul(lhs: Tensor, rhs: Tensor) -> Tensor: ...
def sum(input: Tensor, dim: Optional[int] = ..., keepdim: bool = ...) -> Tensor: ...
def mean(input: Tensor, dim: Optional[int] = ..., keepdim: bool = ...) -> Tensor: ...
def reshape(input: Tensor, shape: Shape) -> Tensor: ...
def squeeze(input: Tensor, dim: Optional[int] = ...) -> Tensor: ...
def unsqueeze(input: Tensor, dim: int) -> Tensor: ...
def no_grad() -> ContextDecorator: ...
def enable_grad() -> ContextDecorator: ...
def set_grad_enabled(enabled: bool) -> ContextDecorator: ...
def is_grad_enabled() -> bool: ...
def manual_seed(seed: int) -> int: ...
def initial_seed() -> int: ...
def save(obj: Any, path: Union[str, PathLike[str]]) -> None: ...
def load(
    path: Union[str, PathLike[str]], map_location: Optional[Any] = ...
) -> Any: ...
def version() -> str: ...

from . import nn as nn
from . import optim as optim
