from os import PathLike
from typing import Any, Optional, Union

def save(obj: Any, path: Union[str, PathLike[str]]) -> None: ...
def load(
    path: Union[str, PathLike[str]], map_location: Optional[Any] = ...
) -> Any: ...
