from collections import OrderedDict
from typing import Any, Iterable, Iterator, Mapping, NamedTuple, Optional, Tuple

from .. import Tensor
from . import functional as functional

class _IncompatibleKeys(NamedTuple):
    missing_keys: list[str]
    unexpected_keys: list[str]

class Parameter(Tensor):
    def __new__(
        cls, data: Any = ..., requires_grad: bool = ...
    ) -> Parameter: ...

class Module:
    training: bool
    def __init__(self) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def forward(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_parameter(
        self, name: str, parameter: Optional[Tensor]
    ) -> None: ...
    def register_buffer(
        self,
        name: str,
        tensor: Optional[Tensor],
        persistent: bool = ...,
    ) -> None: ...
    def add_module(self, name: str, module: Optional[Module]) -> None: ...
    def parameters(self, recurse: bool = ...) -> Iterator[Tensor]: ...
    def named_parameters(
        self, prefix: str = ..., recurse: bool = ...
    ) -> Iterator[Tuple[str, Tensor]]: ...
    def buffers(self, recurse: bool = ...) -> Iterator[Tensor]: ...
    def named_buffers(
        self, prefix: str = ..., recurse: bool = ...
    ) -> Iterator[Tuple[str, Tensor]]: ...
    def children(self) -> Iterator[Module]: ...
    def named_children(self) -> Iterator[Tuple[str, Module]]: ...
    def modules(self) -> Iterator[Module]: ...
    def train(self, mode: bool = ...) -> Module: ...
    def eval(self) -> Module: ...
    def zero_grad(self) -> None: ...
    def to(self, device: Any = ..., dtype: Any = ...) -> Module: ...
    def cpu(self) -> Module: ...
    def cuda(self, device: int = ...) -> Module: ...
    def float(self) -> Module: ...
    def double(self) -> Module: ...
    def bfloat16(self) -> Module: ...
    def state_dict(self) -> OrderedDict[str, Tensor]: ...
    def load_state_dict(
        self, state_dict: Mapping[str, Tensor], strict: bool = ...
    ) -> _IncompatibleKeys: ...

class Linear(Module):
    in_features: int
    out_features: int
    weight: Parameter
    bias: Optional[Parameter]
    def __init__(
        self,
        in_features: int,
        out_features: int,
        bias: bool = ...,
        device: Any = ...,
        dtype: Any = ...,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class Sequential(Module):
    def __init__(self, *modules: Module) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Module]: ...
    def __getitem__(self, index: int) -> Module: ...

class ModuleList(Module):
    def __init__(self, modules: Optional[Iterable[Module]] = ...) -> None: ...
    def append(self, module: Module) -> ModuleList: ...
    def extend(self, modules: Iterable[Module]) -> ModuleList: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Module]: ...
    def __getitem__(self, index: int) -> Module: ...

class Identity(Module):
    def forward(self, input: Tensor) -> Tensor: ...

class ReLU(Module):
    def forward(self, input: Tensor) -> Tensor: ...

class GELU(Module):
    def forward(self, input: Tensor) -> Tensor: ...

class Sigmoid(Module):
    def forward(self, input: Tensor) -> Tensor: ...

class Tanh(Module):
    def forward(self, input: Tensor) -> Tensor: ...

class Flatten(Module):
    start_dim: int
    end_dim: int
    def __init__(self, start_dim: int = ..., end_dim: int = ...) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class LayerNorm(Module):
    normalized_shape: int
    eps: float
    elementwise_affine: bool
    weight: Optional[Parameter]
    bias: Optional[Parameter]
    def __init__(
        self,
        normalized_shape: int,
        eps: float = ...,
        elementwise_affine: bool = ...,
        device: Any = ...,
        dtype: Any = ...,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class RMSNorm(Module):
    normalized_shape: int
    eps: float
    elementwise_affine: bool
    weight: Optional[Parameter]
    def __init__(
        self,
        normalized_shape: int,
        eps: float = ...,
        elementwise_affine: bool = ...,
        device: Any = ...,
        dtype: Any = ...,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class MSELoss(Module):
    def forward(self, input: Tensor, target: Tensor) -> Tensor: ...
