from typing import Optional

from .. import Tensor

def linear(
    input: Tensor, weight: Tensor, bias: Optional[Tensor] = ...
) -> Tensor: ...
def relu(input: Tensor) -> Tensor: ...
def gelu(input: Tensor) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def mse_loss(input: Tensor, target: Tensor) -> Tensor: ...
def layer_norm(
    input: Tensor,
    weight: Optional[Tensor] = ...,
    bias: Optional[Tensor] = ...,
    eps: float = ...,
) -> Tensor: ...
def rms_norm(
    input: Tensor, weight: Optional[Tensor] = ..., eps: float = ...
) -> Tensor: ...
